version: '3.8'

services:
  wg-server:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: ${CONTAINERNAME}
    networks:
      - wg-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${SERVERURL}
      - SERVERPORT=${SERVERPORT}
      - PEERS=${PEERS}
      - PEERDNS=${PEERDNS}
      - ALLOWEDIPS=${ALLOWEDIPS}
      - LOG_CONFS=${LOG_CONFS}
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - ${SERVERPORT}:${SERVERPORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - ${DNSUIPORT}:3000
    volumes:
      - ./adguard_data:/opt/adguardhome/work
      - ./adguard_config:/opt/adguardhome/conf
    networks:
      wg-server:
        ipv4_address: ${PEERDNS}

networks:
  wg-server:
    name: wg-server
    ipam:
      driver: default
      config:
        - subnet: ${SERVERSUBNET}
