version: '3.8'

services:
  wg-server:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: ${CONTAINERNAME}
    networks:
      - wg-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${SERVERURL}
      - SERVERPORT=${SERVERPORT}
      - PEERS=${PEERS}
      - PEERDNS=${PEERDNS}
      - ALLOWEDIPS=${ALLOWEDIPS}
      - LOG_CONFS=${LOG_CONFS}
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - ${SERVERPORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

networks:
  wg-server:
